generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Rates
    theme:            default
    css:     /sf/sf_admin/css/admin_main.css
    list:
      display: [tital,standard_package_rates,premium_package_rates]
      max_per_page: 10000
      fields:
           tital : {name: Title}
      object_actions:
        _edit: ~
    edit:
      display: [tital,standard_package_rates,premium_package_rates]
      fields:
           tital : {name: Title}