generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      TelintaRoutingplan
    theme:            default
    css:     /sf/sf_admin/css/admin_main.css
    list:
      display: [i_routing_plan,title,created_at]
      max_per_page: 100
      object_actions:
        _edit: ~
    edit:
      display: [i_routing_plan,title]