generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      PricePlan
    theme:            default
    css:             /sf/sf_admin/css/admin_main.css
    edit:
      title: Create/Edit Line Quality
      display: [title,telinta_product_id,telinta_routingplan_id]
      fields:
              telinta_routingplan: {name: Telinta Rounting Plan}
    list:
      title:    Line Quality
      display: [title,telinta_product,telinta_routingplan]  
      fields:
              telinta_routingplan: {name: Telinta Rounting Plan}
      max_per_page: 100
      object_actions:
        _edit: ~
        _delete: ~

