generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      User
    theme:            default
    css:             /sf/sf_admin/css/admin_main.css
    list:
      display: [name, email, password, role, is_super_user, create_date]
      object_actions:
        _edit: ~
