# default rules
homepage:
  url:   /
  param: { module: company, action: dashboard }

default_index:
  url:   /:module
  param: { action: dashboard }

login:
  url: /login
  param: {module: company, action:login}

default:
  url:   /:module/:action/*



